const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("winplate", {
  showMainWindow: (section = "Dashboard") => ipcRenderer.send("window:show-main", section),
  onNavigate: (callback) => ipcRenderer.on("main:navigate", (_event, section) => callback(section)),
  openGithubProfile: (url) => ipcRenderer.send("github:open-profile", url),
  refreshGithub: () => ipcRenderer.invoke("github:refresh"),
  getStatus: () => ipcRenderer.invoke("status:get"),
  getNetworkSpeed: () => ipcRenderer.invoke("network:speed"),
  setWeatherLocation: (location) => ipcRenderer.invoke("weather:set-location", location),
  getWeatherSettings: () => ipcRenderer.invoke("weather:get-settings"),
  saveWeatherSettings: (settings) => ipcRenderer.invoke("weather:save-settings", settings),
  getQWeatherUsage: () => ipcRenderer.invoke("weather:get-usage"),
  refreshQWeatherOfficialStats: () => ipcRenderer.invoke("weather:refresh-official-usage"),
  refreshQWeatherAlerts: () => ipcRenderer.invoke("weather:refresh-alerts"),
  getMailSettings: () => ipcRenderer.invoke("mail:get-settings"),
  saveMailSettings: (settings) => ipcRenderer.invoke("mail:save-settings", settings),
  getMailOutline: () => ipcRenderer.invoke("mail:get-outline"),
  refreshMailOutline: () => ipcRenderer.invoke("mail:refresh"),
  connectMail: () => ipcRenderer.invoke("mail:connect"),
  "email:read-message": (uid) => ipcRenderer.invoke("email:read-message", uid),
  openMail: () => ipcRenderer.invoke("mail:open"),
  getNotifications: () => ipcRenderer.invoke("notifications:get"),
  markNotificationRead: (id) => ipcRenderer.invoke("notifications:mark-read", id),
  markAllNotificationsRead: () => ipcRenderer.invoke("notifications:mark-all-read"),
  pushTestNotification: () => ipcRenderer.invoke("notifications:push-test"),
  getAppearanceSettings: () => ipcRenderer.invoke("appearance:get-settings"),
  saveAppearanceSettings: (settings) => ipcRenderer.invoke("appearance:save-settings", settings),
  getCodexUsage: (options = {}) => ipcRenderer.invoke("codex:usage", options),
  getDeepSeekSettings: () => ipcRenderer.invoke("deepseek:get-settings"),
  saveDeepSeekSettings: (settings) => ipcRenderer.invoke("deepseek:save-settings", settings),
  getDeepSeekUsage: (options = {}) => ipcRenderer.invoke("deepseek:usage", options),
  setWindowTheme: (theme) => ipcRenderer.send("window:set-theme", theme),
  minimizeWindow: () => ipcRenderer.send("window:minimize"),
  toggleMaximizeWindow: () => ipcRenderer.invoke("window:toggle-maximize"),
  closeWindow: () => ipcRenderer.send("window:close"),
  onMaximizedChange: (callback) => ipcRenderer.on("window:maximized", (_event, value) => callback(value)),

  setFloatingPinned: (value) => ipcRenderer.invoke("floating:set-pinned", value),
  setFloatingPinInteractive: (value) => ipcRenderer.send("floating:pin-interactive", value),
  showTooltip: (payload) => ipcRenderer.send("tooltip:show", payload),
  hideTooltip: () => ipcRenderer.send("tooltip:hide"),
  onTooltipUpdate: (callback) => ipcRenderer.on("tooltip:update", (_event, data) => callback(data))
});
