const { contextBridge, ipcRenderer } = require("electron");

const platform = ["darwin", "win32"].includes(process.platform)
  ? process.platform
  : "unsupported";

contextBridge.exposeInMainWorld("winplate", {
  platform,
  showMainWindow: (section = "Dashboard") => ipcRenderer.send("window:show-main", section),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings),
  onSettingsUpdated: (callback) => ipcRenderer.on("settings:updated", (_event, settings) => callback(settings)),
  onNavigate: (callback) => ipcRenderer.on("main:navigate", (_event, payload) => callback(payload)),
  openGithubProfile: (url) => ipcRenderer.send("github:open-profile", url),
  refreshGithub: () => ipcRenderer.invoke("github:refresh"),
  getGithubContributions: (range) => ipcRenderer.invoke("github:get-contributions", range),
  getStatus: () => ipcRenderer.invoke("status:get"),
  getNetworkSpeed: () => ipcRenderer.invoke("network:speed"),
  setWeatherLocation: (location) => ipcRenderer.invoke("weather:set-location", location),
  searchWeatherLocations: (query) => ipcRenderer.invoke("weather:search-locations", query),
  setManualWeatherLocation: (location) => ipcRenderer.invoke("weather:set-manual-location", location),
  getWeatherSettings: () => ipcRenderer.invoke("weather:get-settings"),
  saveWeatherSettings: (settings) => ipcRenderer.invoke("weather:save-settings", settings),
  getQWeatherUsage: () => ipcRenderer.invoke("weather:get-usage"),
  getQWeatherAlerts: () => ipcRenderer.invoke("weather:get-alerts"),
  refreshQWeatherOfficialStats: () => ipcRenderer.invoke("weather:refresh-official-usage"),
  refreshQWeatherAlerts: () => ipcRenderer.invoke("weather:refresh-alerts"),
  onStatusRefresh: (callback) => ipcRenderer.on("status:refresh", (_event, payload) => callback(payload)),
  getMailSettings: () => ipcRenderer.invoke("mail:get-settings"),
  saveMailSettings: (settings) => ipcRenderer.invoke("mail:save-settings", settings),
  getMailOutline: () => ipcRenderer.invoke("mail:get-outline"),
  refreshMailOutline: () => ipcRenderer.invoke("mail:refresh"),
  connectMail: () => ipcRenderer.invoke("mail:connect"),
  getMailMessage: (uid) => ipcRenderer.invoke("mail:get-message", uid),
  "email:read-message": (uid) => ipcRenderer.invoke("email:read-message", uid),
  openMail: () => ipcRenderer.invoke("mail:open"),
  getNotifications: () => ipcRenderer.invoke("notifications:get"),
  getNotificationDigest: () => ipcRenderer.invoke("notification:get-digest"),
  getNotificationDetail: (id) => ipcRenderer.invoke("notifications:get-detail", id),
  navigateNotification: (action) => ipcRenderer.invoke("notifications:navigate", action),
  copyNotificationText: (text) => ipcRenderer.invoke("notifications:copy", text),
  onNotificationDigestUpdated: (callback) => ipcRenderer.on("notification:digest-updated", (_event, digest) => callback(digest)),
  getSmartBrief: () => ipcRenderer.invoke("notifications:get-smart-brief"),
  refreshSmartBrief: () => ipcRenderer.invoke("notifications:refresh-smart-brief"),
  markNotificationRead: (id) => ipcRenderer.invoke("notifications:mark-read", id),
  markAllNotificationsRead: () => ipcRenderer.invoke("notifications:mark-all-read"),
  clearNotifications: () => ipcRenderer.invoke("notifications:clear"),
  pushTestNotification: () => ipcRenderer.invoke("notifications:push-test"),
  getAppearanceSettings: () => ipcRenderer.invoke("appearance:get-settings"),
  saveAppearanceSettings: (settings) => ipcRenderer.invoke("appearance:save-settings", settings),
  getAppSettings: () => ipcRenderer.invoke("app:get-settings"),
  saveAppSettings: (settings) => ipcRenderer.invoke("app:save-settings", settings),
  getCodexUsage: (options = {}) => ipcRenderer.invoke("codex:usage", options),
  getDeepSeekSettings: () => ipcRenderer.invoke("deepseek:get-settings"),
  saveDeepSeekSettings: (settings) => ipcRenderer.invoke("deepseek:save-settings", settings),
  getDeepSeekUsage: (options = {}) => ipcRenderer.invoke("deepseek:usage", options),
  testDeepSeekChat: () => ipcRenderer.invoke("deepseek:test-chat"),
  setWindowTheme: (theme) => ipcRenderer.send("window:set-theme", theme),
  minimizeWindow: () => ipcRenderer.send("window:minimize"),
  toggleMaximizeWindow: () => ipcRenderer.invoke("window:toggle-maximize"),
  closeWindow: () => ipcRenderer.send("window:close"),
  onMaximizedChange: (callback) => ipcRenderer.on("window:maximized", (_event, value) => callback(value)),

  ...(platform === "win32" ? {
    setFloatingPinned: (value) => ipcRenderer.invoke("floating:set-pinned", value),
    setFloatingPinInteractive: (value) => ipcRenderer.send("floating:pin-interactive", value),
    showTooltip: (payload) => ipcRenderer.send("tooltip:show", payload),
    hideTooltip: () => ipcRenderer.send("tooltip:hide"),
    onTooltipUpdate: (callback) => ipcRenderer.on("tooltip:update", (_event, data) => callback(data))
  } : {})
});
